name: Close Issue Telegram Notify

on:
  issues:
    types:
      - closed

jobs:
  notify_issue_close:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Notify closed issue on telegram group
        uses: appleboy/telegram-action@221e6b684967abe813051ee4a37dd61770a83ad3 # v1.0.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_KEY }}
          disable_web_page_preview: true
          message: |
            ✅ Issue chiusa in ${{ github.repository }}
            ${{ github.event.issue.title }}
            da ${{ github.actor }}

            ${{ github.event.issue.html_url }}
