name: Job Day

on:
  schedule:
    - cron: "0 8 * * 3"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  send:
    name: Send job day post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: functions/.nvmrc
          cache: npm
          cache-dependency-path: functions/package-lock.json
      - name: Install dependencies
        working-directory: functions
        run: npm ci
      - name: Send job day post
        working-directory: functions
        env:
          TELEGRAM_BOT_KEY: ${{ secrets.TELEGRAM_BOT_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: npx tsx scripts/job-day.ts
