name: Open Issue Telegram Notify

on:
  issues:
    types:
      - reopened
      - opened

permissions: {}

jobs:
  notify_issue_open:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Notify new issue on telegram group
        uses: appleboy/telegram-action@221e6b684967abe813051ee4a37dd61770a83ad3 # v1.0.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_KEY }}
          disable_web_page_preview: true
          message: |
            🐛 Nuova issue in ${{ github.repository }}
            ${{ github.event.issue.title }}
            aperta da ${{ github.actor }}

            ${{ github.event.issue.html_url }}

            Partecipa e vota le decisioni del gruppo: https://github.com/${{ github.repository }}/issues
